### ISSUE TITLE
Error: The requested accessory 'Httpdoor' was not registered by any plugin.

### ISSUE THREAD

**Issue by johandk89** [EricConnerApps/homebridge-httpdoor#1]
When starting homebridge I receive this error: 

```
/usr/local/lib/node_modules/homebridge/lib/api.js:60
      throw new Error("The requested accessory '" + name + "' was not registered by any plugin.");
      ^

Error: The requested accessory 'Httpdoor' was not registered by any plugin.
    at API.accessory (/usr/local/lib/node_modules/homebridge/lib/api.js:60:13)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:233:42)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:72:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:434:26)
    at Object.Module._extensions..js (module.js:452:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:475:10)
```

This is part of my config file

```
    {
            "accessory": "Httpdoor",
            "name": "Left garage door",
            "controlURL": "Some-url",
            "statusURL": "Some-url"
    }
```

**Comment by eaconner** [comment]
I just verified that everything is working and the config you provided is correct. It looks like homebridge-httpdoor is not installed or detected by Homebridge. I would verify that it is installed 'npm install -g homebridge-httpdoor'. If that doesn't fix it, I would recommend deleting the  'persist/' and 'accessories/' directories.

**Comment by johandk89** [comment]
Thanks, its working now

**Comment by toshibochan** [comment]
@johandk89 what hardware you use for door lock?

**Comment by toshibochan** [comment]
i want use servo motor and Raspberry PI or ESP8266, but i don't find any tutorial on the web. Any tutorial you guys know?

**Comment by toshibochan** [comment]
Hi @johandk89 what hardware you using for the door?
